import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { SiGoogle } from "react-icons/si";
import BusinessCard from "../components/BusinessCard/BusinessCard";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<div className="flex h-[calc(100vh-4rem)] flex-col items-center justify-center bg-gradient-to-br from-green-600 to-blue-800">
        {!sessionData && (
          <button
            onClick={sessionData ? () => signOut() : () => signIn("google")}
            className="max-w-max rounded-lg bg-zinc-100 py-2 px-6 text-zinc-900 duration-200 hover:shadow-xl dark:bg-zinc-900 dark:text-zinc-100">
            <SiGoogle className="mr-2 inline-block" />
            Sign in
          </button>
        )}
        </div> */}
      <div className="flex h-full min-h-full w-full flex-col py-6">
        {!sessionData && (
          <div className="flex flex-col gap-2 rounded-lg bg-gradient-to-r from-neutral-200 to-zinc-200 p-4 shadow-xl dark:bg-gradient-to-r dark:from-neutral-800 dark:to-zinc-800">
            <div>
              <h3 className="m-0 text-zinc-800 dark:text-zinc-200">
                Leave a Message 👇
              </h3>
              <p className="m-0 text-sm text-zinc-700 dark:text-zinc-300">
                You need to be signed in to post a message.
              </p>
            </div>
            <div className="flex gap-2">
              <button
                className="max-w-max rounded-lg bg-zinc-100 py-2 px-6 text-zinc-900 duration-200 hover:shadow-xl dark:bg-zinc-900 dark:text-zinc-100 "
                onClick={
                  sessionData ? () => signOut() : () => signIn("google")
                }>
                <SiGoogle className="mr-2 inline-block" />
                Sign In
              </button>
            </div>
          </div>
        )}

        {/**Main Business card */}
        {sessionData && (
          <div className="flex flex-col items-center justify-center">
            <BusinessCard />
          </div>
        )}
      </div>
    </div>
  );
};

export default Home;
